const data = [
    {
        "id": 1,
        "title": "Fate/stay night Movie: Heaven's Feel - III. Spring Song",
        "description": "Fate / stay night Movie: Heaven’s Feel III. Spring Song là chương cuối cùng theo route 3 của bộ ba Fate/Stay Night. Bộ anime ấy chủ đề “Cuộc Chiến Chén Thánh”: một cuộc chiến dữ dội kéo dài qua nhiều thế hệ giữa các pháp sư, trong đó 7 Master và 7 Servant được triệu tập cùng nhau chiến đấu giành Chén Thánh, một vật phẩm ma thuật có thể ban cho người chiến thắng bất kỳ điều ước nào.",
        "image_title": "/resources/img/slide-banner-5.jpg",
        "image_banner": "/resources/img/Banner-Fate-Stay-Night-Heavens-Feel-I-Presage-Flower.jpg",
        "video": "https://video.fhph1-1.fna.fbcdn.net/v/t66.36240-6/10000000_938456473746288_6302216283377414040_n.mp4?_nc_cat=102&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=QA4YesjLz_oAX_huy1g&rl=1500&vabr=722&_nc_ht=scontent-frt3-1.xx&oh=fdeccaa62c9b1b41a0b4cf4bad690c36&oe=618FBBFA",
        "episode": 1,
        "link_info": "/info/info-fate-stay-night-heaven-feel.html",
        "link_watch": "/watch/watch-fate-stay-night-heaven-feel.html",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 122,
        "rating": 9.5,
        "user_rating": 230,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hành động",
            "Viễn tưởng",
            "Ma thuật",
            "Fantasy"
        ],
        "year": 2020
    },
    {
        "id": 2,
        "title": "Platinum End",
        "description": "Khi các bạn cùng lớp ăn mừng lễ tốt nghiệp cao trung, Mirai đã gặp rắc rối chìm trong bóng tối. Nhưng trận chiến của cậu ta chỉ mới bắt đầu khi nhận được sự cứu rỗi nào đó từ thiên giới dưới hình dạng một thiên thần. Giờ đây, Mirai đang đọ sức với 12 người được chọn khác trong một trận chiến mà người chiến thắng trở thành vị thần tiếp theo của thế giới. Mirai có một thiên thần trong thể xác của mình, nhưng cậu có thể cần phải trở thành ác quỷ để tồn tại.",
        "image_title": "/resources/img/Platinum End.jpg",
        "image_banner": "https://i0.wp.com/ikigaipop.com/wp-content/uploads/2021/08/platinum-end-anime-cover.jpeg?resize=1068%2C580&ssl=1",
        "video": "https://scontent-ams4-1.xx.fbcdn.net/v/t66.36240-6/10000000_423430512672180_1907598410666081371_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=ayZR493yoMIAX8CXVUU&rl=1500&vabr=878&_nc_ht=scontent-ams4-1.xx&edm=APRAPSkEAAAA&oh=2a166a8561831793c45f7c8796cd85f6&oe=619184D3",
        "episode": 1,
        "link_info": "/info/info-platinum-end.html",
        "link_watch": "/watch/watch-platinum-end.html",
        "episode_lastes": 5,
        "episodes": 25,
        "time": 24,
        "rating": 9.5,
        "user_rating": 151,
        "view": 243390,
        "studio": "Signal.MD, Magic Capsule",
        "age_limit": 13,
        "love": 1217,
        "status": false,
        "type": [
            "Hành động",
            "Drama",
            "Siêu nhiên"
        ],
        "year": 2021,
    },
    {
        "id": 3,
        "title": "Evangelion: 3.0 + 1.0 You Are (Not) Alone",
        "description": "Sau năm 2000, một phần thế giới đã bị phá hủy bởi một sinh vật gọi là ADAM, sự kiện này gọi là '2nd IMPACT'. Ikari Shinji là một cậu bé mồ côi mẹ, và rất ghét cha mình, người mà Shinji đã không gặp trong nhiều năm. Một hôm vào năm 2015, Shinji nhận được lệnh của cha và đến Neo Tokyo-3. Shinji chứng kiến một sinh vật khổng lồ gọi là ANGEL tấn công thành phố; cậu được một phụ nữ tên là Misato đón và đưa đến một căn cứ bí mật dưới lòng đất gọi là NERV, nơi mà cha cậu đang là chỉ huy. Shinji được lệnh phải lái một robot để chiến đấu chống lại ANGEL, và cậu không đồng ý. Tuy nhiên khi chứng kiến Ayanami Rei, một cô gái nhỏ nhắn đang bị thương tích đầy mình phải vào buồng lái, Shinji chấp nhận thay thế và trèo vào robot EVA để chiến đấu chống lại ANGEL.",
        "image_title": "/resources/img/slide-banner-11.jpg",
        "image_banner": "https://c4.wallpaperflare.com/wallpaper/652/839/701/neon-genesis-evangelion-eva-unit-01-eva-unit-02-eva-unit-00-wallpaper-preview.jpg",
        "video": "https://www813.ff-02.com/token=4r6E1f5pMxBXHz7A1mWa4g/1636652000/2001:ee0::/176/8/8a/fb7cb89232181c46bfa51712f859b8a8-1080p.mp4",
        "episode": 1,
        "link_info": "/info/info-evangelion.html",
        "link_watch": "/watch/watch-evangelion.html",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 100,
        "rating": 9.2,
        "user_rating": 55,
        "view": 243390,
        "studio": "Xapa",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hành động",
            "Viễn tưởng",
            "Mecha",
            "Drama"
        ],
        "year": 2021,
    },
    {
        "id": 4,
        "title": "Shuumatsu Nani Shitemasu ka? Isogashii desu ka? Sukutte Moratte Ii desu ka?",
        "description": "Nam chính tỉnh giấc sau 500 năm kể từ cuộc chiến cuối cùng, mất tất cả bất lực để rồi trở thành Papa của mấy bé loli có sức mạnh, và từ đó kiếm tìm ý nghĩa của hạnh phúc gia đình, trải nghiệm vâng vâng và vâng vâng... có lẽ theo chiều hướng bi tráng.",
        "image_title": "/resources/img/slide-banner-10.jpg",
        "image_banner": "https://c4.wallpaperflare.com/wallpaper/490/923/734/anime-sukasuka-almita-sukasuka-chtholly-nota-seniorious-wallpaper-preview.jpg",
        "video": "https://video-ams4-1.xx.fbcdn.net/v/t42.1790-2/10000000_337960767794990_2376938166845310946_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjMwMCwicmxhIjo0MDc3LCJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=GlFd_Pz3Lz8AX-tLVrC&rl=300&vabr=150&_nc_ht=video-ams4-1.xx&edm=APRAPSkEAAAA&oh=771a529f921459233d2f38db2abc4411&oe=618EC667",
        "episode": 1,
        "link_info": "/info/info-sukasuka.html",
        "link_watch": "/watch/watch-sukasuka.html",
        "episode_lastes": 12,
        "episodes": 12,
        "time": 24,
        "rating": 9.7,
        "user_rating": 1393,
        "view": 243390,
        "studio": "Satelight, C2C",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Tình cảm",
            "Viễn tưởng",
            "Drama",
            "Fantasy"
        ],
        "year": 2017,
    },
    {
        "id": 5,
        "title": "Mushoku Tensei: Jobless Reincarnation",
        "description": "Mình sẽ sống nghiêm túc tại thế giới này'!'\
        Một ông chú fap sư 34 tuổi, thất nghiệp, làm NEET là chính.\
        Ngay sau khi chú ta bị đá ra khỏi nhà vào cái ngày đưa tang song thân phụ mẫu, truck- kun chào đón chú ta và tiễn về thế giới khác.\
        Khi giật mình tỉnh giấc chú ta nhận ra bản thân đã đầu thai thành đứa bé sống trong thế giới của Kiếm và Ma pháp.\
        Gã đàn ông từng sống như thứ rác rưởi thề nguyện rằng\
        Trong thế giới mới này, trong nhân dạng Rudeus này, tôi sẽ sống thật nghiêm túc!\
        Rudeus gặp gỡ Ma thuật sư bé con Roxy, cô / cậu bé đẹp gái / trai có đôi tai như người Elf, và tiểu thư tsundere bà chằn.\
        Va chạm với nhiều loại hạng người.Và đấu tranh trong những chuyến mạo hiểm đầy khốc liệt.\
        Cuộc sống mới bắt đầu vận hành!\
        Chuyện huyễn tưởng làm lại cuộc đời, BẮT ĐẦU!",
        "image_title": "/resources/img/slide-banner-3.jpg",
        "image_banner": "https://ecdn.game4v.com/g4v-content/uploads/2020/12/Mushoku-Tensei-anime-01-game4v.jpg",
        "video": "https://scontent-ams4-1.xx.fbcdn.net/v/t66.36240-6/10000000_627128908631296_7300722905748471613_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=D8I3HpEShTMAX86F143&rl=1500&vabr=828&_nc_ht=scontent-ams4-1.xx&edm=APRAPSkEAAAA&oh=777999ab674c01008feef25323d860fc&oe=619236DE",
        "episode": 1,
        "link_info": "/info/info-mushoku-tensei.html",
        "link_watch": "/watch/watch-mushoku-tensei.html",
        "episode_lastes": 5,
        "episodes": 12,
        "time": 24,
        "rating": 9.1,
        "user_rating": 631,
        "view": 243390,
        "studio": "Bind",
        "age_limit": 12,
        "love": 1217,
        "status": false,
        "type": [
            "Tình cảm",
            "Isekai",
            "Viễn tưởng",
            "Harem",
            "Phiêu lưu",
            "Phép thuật",
            "Hành động"
        ],
        "year": 2021,
    },
    {
        "id": 6,
        "title": "Sekai Saikou no Ansatsusha, Isekai Kizoku ni Tensei suru",
        "description": "“Tôi sẽ sống cho chính mình!” Sát thủ vĩ đại nhất trên trái đất chỉ biết sống như một công cụ cho chủ nhân– cho đến khi họ quyết định giết ông. Được tái sinh bởi ân sủng của một nữ thần vào thế giới của kiếm và phép thuật, lần này ông ta có cơ hội để làm những điều khác đi, nhưng có một yêu cầu… Ông ta phải loại bỏ một anh hùng siêu mạnh, người nếu không bị ngăn chặn thì sẽ khiến thế giới diệt vong. Anh hùng được biết đến với cái tên Lugh Tuatha Dé, người khiến cả sát thủ bậc thầy cũng phải bất lực, nhất là vì những cô gái xinh đẹp mạnh mẽ luôn vây quanh anh ta. Dù là một sát thủ bậc thầy, nhưng ông ta sẽ xử trí thế nào tại thế giới chỉ có kiếm và phép thuật?",
        "image_title": "/resources/img/Sekai Saikou no Ansatsusha- Isekai Kizoku ni Tensei suru.jpg",
        "image_banner": "/resources/img/Sekai Saikou no Ansatsusha- Isekai Kizoku ni Tensei suru.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_424663825690294_2884080993526559328_n.mp4?_nc_cat=103&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=Y1flKocTMa0AX_2XcBB&rl=1500&vabr=870&_nc_ht=scontent-frt3-2.xx&oh=38518c8351005e738a3515233ad1ddfd&oe=618A8A35",
        "episode": 1,
        "link_info": "/info/info-sekai-saikou-no-ansatsusha-isekai-kizoku-ni-tensei-suru.html",
        "link_watch": "#",
        "episode_lastes": 5,
        "episodes": 12,
        "time": 24,
        "rating": 9.6,
        "user_rating": 661,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Isekai",
            "Viễn tưởng",
            "Phép thuật",
            "Hành động"
        ],
        "year": 2021,
    },
    {
        "id": 7,
        "title": "Takt Op. Destiny",
        "description": "Xoay quanh câu chuyện về Takt, một nhạc trưởng, đã hợp tác với một Musicart tên Unmei. Cậu mong muốn âm nhạc được quay trở lại thế giới, còn Unmei mong muốn phá hủy D2. Vì thế cả hai đã cùng đồng hành để có thể thực hiện mục tiêu của mỗi người.",
        "image_title": "/resources/img/slide-banner-1.jpg",
        "image_banner": "/resources/img/slide-banner-1.jpg",
        "video": "https://video.fhph1-1.fna.fbcdn.net/v/t66.36240-6/10000000_1236395650175290_384590104309028518_n.mp4?_nc_cat=100&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=Y52-NYez6CwAX-eSBJR&rl=1500&vabr=982&_nc_ht=scontent-frx5-1.xx&oh=b4068ef0be3ca7e69bb245c756885e84&oe=618AA63D",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 4,
        "episodes": 12,
        "time": 24,
        "rating": 9.6,
        "user_rating": 458,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Viễn tưởng",
            "Âm nhạc",
            "Hành động"
        ],
        "year": 2021,
    },
    {
        "id": 8,
        "title": "Kimetsu no Yaiba : Mugen Ressha-hen",
        "description": "Trong movie lần này, Viêm Trụ sẽ là nhân vật trung tâm của toàn bộ câu chuyện. Bên cạnh đó, bộ tứ anh em nhà Tanjirou – Nezuko, Zenitsu và Inosuke cũng có màn trình diễn gây ấn tượng không kém. Lần này, phe thợ săn quỷ sẽ trực tiếp đối đầu với Hạ Huyền Nhất sau khi Muzan đã tiêu diệt toàn bộ quỷ Hạ Huyền. Tuy nhiên, ẩn số còn nằm phía sau movie Chuyến tàu vô tận bởi những yếu tố bất ngờ của câu chuyện chỉ mới bắt đầu.",
        "image_title": "/resources/img/slide-banner-2.jpg",
        "image_banner": "https://vnw-img-cdn.popsww.com/api/v2/containers/file2/cms_topic/series_detail_desktop-1c99db3ae6b6-1598848789030-nnCgEgSb.jpg?v=0",
        "video": "https://scontent-ams4-1.xx.fbcdn.net/v/t66.36240-6/10000000_843840789625560_7321380416448712177_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE2NDEsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=mg51b3rw80cAX8-fHbt&rl=1641&vabr=1094&_nc_ht=scontent-ams4-1.xx&edm=APRAPSkEAAAA&oh=c482ea0cde4d1d49b1936753fcf7f27a&oe=6191062D",
        "episode": 1,
        "link_info": "/info/info-kimetsu-no-yaiba.html",
        "link_watch": "/watch/watch-kimetsu-no-yaiba.html",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 116,
        "rating": 9.6,
        "user_rating": 585,
        "view": 243390,
        "studio": "ufotable, Aniplex, Aniplex of America",
        "age_limit": 13,
        "love": 1217,
        "status": true,
        "type": [
            "Viễn tưởng",
            "Drama",
            "Hành động"
        ],
        "year": 2021,
    },
    {
        "id": 9,
        "title": "Re:Zero kara Hajimeru Isekai Seikatsu",
        "description": "1 thanh niên đi mua tạp hóa đang trên đường về bỗng dưng được triệu hồi sang thế giới khác, ở đó anh chết đi lại quay về thời điểm bắt đầu.",
        "image_title": "/resources/img/slide-banner-4.jpg",
        "image_banner": "https://files.virgool.io/upload/users/180680/posts/vvuqum7vyrjz/aj1hllznuxgc.jpeg",
        "video": "https://scontent-amt2-1.xx.fbcdn.net/v/t66.36240-6/10000000_312608520268244_6322886782032689946_n.mp4?_nc_cat=106&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=Ff6yTN5Q0f4AX86IrAP&rl=1500&vabr=563&_nc_ht=scontent-amt2-1.xx&edm=APRAPSkEAAAA&oh=27ebaab9b5e97635e3e2dcc36c590712&oe=619139FF",
        "episode": 1,
        "link_info": "/info/info-re-zero.html",
        "link_watch": "/watch/watch-re-zero.html",
        "episode_lastes": 25,
        "episodes": 25,
        "time": 24,
        "rating": 9.3,
        "user_rating": 2161,
        "view": 243390,
        "studio": "White fox",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Viễn tưởng",
            "Drama",
            "Kinh dị",
            "Tình cảm",
            "Isekai",
            "Phiêu lưu",
            "Hành động",
            "Ma thuật",
            "Fantasy"
        ],
        "year": 2016,
    },
    {
        "id": 10,
        "title": "Attack On Titan - Shingeki No Kyojin",
        "description": "Cuộc chiến của con người chống lại các Titan khổng lồ để giành giật mạng sống của mình. Vài trăm năm trước, con người bắt đầu bị tấn công bởi những người Khổng lồ, một sinh vật ăn thịt người. Đáng ngại thay, chúng ăn con người như một thú vui hơn là nhu cầu ăn uống. Diện tích sống của con người ngày càng thu hẹp dần, họ đành phải xây những bước tường cao đến 60m để ngăn người Khổng lồ cao nhất lúc đó là 15m. Con người tuy sống gò bó trong những bức tường chật hẹp nhưng đổi lại, họ sống yên bình. Nhưng rồi một ngày nọ, tất cả sự yên bình đó đã tan vào hư vô trong phút chốc...",
        "image_title": "/resources/img/slide-banner-7.jpg",
        "image_banner": "https://nawalakarsa.id/wp-content/uploads/2021/01/aot2.jpg",
        "video": "https://www398.ff-01.com/token=dUt5CFylbWPC0kFs2IAQdw/1636652861/2001:ee0::/109/8/f2/378e79422df723d81be77a6464316f28-720p.mp4",
        "episode": 1,
        "link_info": "/info/info-attack-on-titan.html",
        "link_watch": "/watch/watch-attack-on-titan.html",
        "episode_lastes": 25,
        "episodes": 25,
        "time": 24,
        "rating": 9.3,
        "user_rating": 874,
        "view": 243390,
        "studio": "Wit",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Viễn tưởng",
            "Drama",
            "Kinh dị",
            "Hành động"
        ],
        "year": 2013,
    },
    {
        "id": 11,
        "title": "MADE IN ABYSS",
        "description": "Hệ thống hang động khổng lồ, nơi duy nhất trên thế giới còn chưa được khám phá hay còn được biết đến với cái tên, Abyss. Không ai biết được mê cung bí ẩn này sâu xuống bao nhiêu, có những quái vật cũng như di tích nào. Rất nhiều nhà thám hiểm đã dấn thân vào công cuộc thám hiểm nơi đâu. Qua thờii gian, những ai có đủ can đảm để bước xuống mê cung này thường được gọi bằng cái tên Thám hiểm gia hang động.\
        Ở Oosu, thị trấn bên rìa Abyss, có một cô bé mồ côi tên là Rico, nuôi ước trở thành một thám hiểm gia hang động như mẹ cô mà giải được bí ẩn cả Abyss. Một ngày nọ khi đang khám phá những bí ẩn bên dưới Abyss, cô đã gặp được một cậu bé robot...",
        "image_title": "/resources/img/slide-banner-9.jpg",
        "image_banner": "https://www.animenewsnetwork.com/thumbnails/crop1200x630gFY/cms/news/110199/abyss.jpg",
        "video": "https://video-amt2-1.xx.fbcdn.net/v/t42.1790-2/10000000_242952247328752_7211316506979550008_n.mp4?_nc_cat=106&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjMxNiwicmxhIjo0MDk2LCJ2ZW5jb2RlX3RhZyI6InN2ZV9zZCJ9&_nc_ohc=-WyxFSUf3VAAX9JAILI&rl=316&vabr=176&_nc_ht=video-amt2-1.xx&edm=APRAPSkEAAAA&oh=2758eef2e189c75d1cda10c7592c12f0&oe=618DEB66",
        "episode": 1,
        "link_info": "/info/info-made-in-abyss.html",
        "link_watch": "/watch/watch-made-in-abyss.html",
        "episode_lastes": 13,
        "episodes": 13,
        "time": 24,
        "rating": 9.6,
        "user_rating": 254,
        "view": 243390,
        "studio": "Kinema Citrus, Media Factory",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Viễn tưởng",
            "Drama",
            "Fantasy",
            "Phiêu Lưu",
            "Kinh dị"
        ],
        "year": 2017,
    },
    {
        "id": 12,
        "title": "Josee to Tora to Sakana-tachi",
        "description": "Phim xoay quanh cuộc gặp gỡ định mệnh giữa Josee, một cô gái 24 tuổi khuyết tật, sống cùng bà và vô cùng khép kín với cuộc sống bên ngoài. Josee đã luôn sống trong thế giới nhỏ của bản thân, cho tới một buổi tối định mệnh khi cô được cậu sinh viên Tsuneo cứu trong một tai nạn. Mới đầu, Josee còn vô cùng cảnh giác với sự xuất hiện của Tsuneo, tuy nhiên sau đó, khi cậu sinh viên chứng minh được sự chân thành của mình, Josee đã dần mở lòng để Tsuneo khám phá về thế giới bí mật của riêng cô. Về phần Tsuneo, sự xuất hiện của Josee chính là bước ngoặt trong cuộc sống tưởng chừng đã được “mặc định” sẵn từng bước của cậu.",
        "image_title": "/resources/img/slide-banner-8.jpg",
        "image_banner": "/resources/img/slide-banner-8.jpg",
        "video": "https://www639.ff-02.com/token=PtMfqH9XgbO0X2IU4mz6qg/1636177301/2001:ee0::/164/9/14/c4e886e53a2af9a34879d90ca842d149-720p.mp4",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 98,
        "rating": 9.9,
        "user_rating": 913,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Tình cảm",
            "Drama",
            "Đời thường"
        ],
        "year": 2020,
    },
    {
        "id": 13,
        "title": "Kizumonogatari I: Tekketsu-hen",
        "description": "Koyomi Araragi, một học sinh trung học năm thứ hai tại trường trung học Naoetsu, kết bạn với Tsubasa Hanekawa, học sinh giỏi đứng đầu tại trường học của mình. Tsubasa nói đến một tin đồn về 'ma cà rồng tóc vàng' đã có người nhìn thấy xung quanh thị trấn của họ gần đây. Koyomimột người thích làm chuyện không giống ai bắt đàu tìm hiểu Buổi tối hôm đó, Koyomi gặp ma cà rồng tin đồn này cố ấy tên là Kiss-shot và cô gái tóc vàng gào to với Koyomi để cứu cô khi cô nằm trong một vũng máu của mình, cả bốn chân tay của cô bị cắt đứt. Kiss-shot nói với Koyomi cho cô ấy máu của mình để cứu cuộc sống cô, và khi cậu làm xong và tỉnh dậy, Koyomi thấy mình..... thôi coi đi rồi biết 'Chào mừng bạn đến với thế giới của bóng tối ...'",
        "image_title": "/resources/img/slide-banner-6.jpg",
        "image_banner": "/resources/img/Kizumonogatari-poster-1024x538.png",
        "video": "https://scontent-ams4-1.xx.fbcdn.net/v/t66.36240-6/10000000_4796584760352253_4863596042637028584_n.mp4?_nc_cat=104&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=gI5H0t2K5bUAX9Z5Y7S&rl=1500&vabr=779&_nc_ht=scontent-ams4-1.xx&edm=APRAPSkEAAAA&oh=ae7f0cb312bbb98ad8d63bb2f4ca1770&oe=6191E457",
        "episode": 1,
        "link_info": "/info/info-kizumonogatari.html",
        "link_watch": "/watch/watch-kizumonogatari.html",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 63,
        "rating": 9.7,
        "user_rating": 118,
        "view": 243390,
        "studio": "Shaff",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hành động",
            "Drama",
            "Kinh dị",
            "Siêu nhiên"
        ],
        "year": 2016,
    },
    {
        "id": 14,
        "title": "Darling in the FranXX",
        "description": "Họ mơ ước một ngày bay vào bầu trời vô tận, mặc dù họ đang đau đớn nhận thức được làm thế nào xa bầu trời là ngoài thủy tinh mà khối chuyến bay của họ. Tương lai xa vời: Nhân loại đã thành lập thành phố pháo đài di động, Plantation, trên nền đất hoang vắng và nền văn minh phát triển rực rỡ. Trong thành phố là những khu thí điểm được gọi là Mistilteinn, còn được gọi là \"Birdcage\". Đó là nơi bọn trẻ sống ... Không biết bất cứ điều gì của thế giới bên ngoài và không biết đến bầu trời rộng lớn. Nhiệm vụ duy nhất của họ trong cuộc đời là cuộc chiến. Kẻ thù của họ là những sinh vật khổng lồ bí ẩn được gọi là Kyoryu. Trẻ em điều khiển các robot được gọi là FRANXX để đối mặt với những kẻ thù chưa thấy đó bởi vì họ tin rằng đó là mục đích của chúng trong cuộc sống. Trong số đó có một cậu bé đã từng được gọi là một thần đồng: Mã số 016, Hiro. Tuy nhiên, bây giờ anh ta là một thất bại và được coi là không cần thiết. Những người không thể thí điểm FRANXX cơ bản không tồn tại. Một ngày kia, một cô gái bí ẩn tên Zero Two xuất hiện trước Hiro. Từ khuôn mặt cô ấy đã có hai chiếc sừng lôi cuốn. \"Tôi đã tìm thấy bạn, Darling của tôi.\"",
        "image_title": "/resources/img/Darling in the FranXX.jpg",
        "image_banner": "/resources/img/Darling in the FranXX.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_612208256458372_9118228228819890916_n.mp4?_nc_cat=110&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=IOEvxVBAsHIAX_Wo45K&rl=1500&vabr=748&_nc_ht=scontent-frx5-1.xx&oh=8529060c972b6ba7803794a930c2895f&oe=618B312D",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 24,
        "episodes": 24,
        "time": 24,
        "rating": 9.5,
        "user_rating": 5657,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Viễn tưởng",
            "Mecha",
            "Tình cảm",
            "Drama"
        ],
        "year": 2018,
    },
    {
        "id": 15,
        "title": "Kobayashi-san Chi no Maid Dragon S",
        "description": "Phần hai của Kobayashi-san Chi no Maid Dragon",
        "image_title": "/resources/img/Kobayashi-san Chi no Maid Dragon S.jpg",
        "image_banner": "/resources/img/Kobayashi-san Chi no Maid Dragon S.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_607523847056445_1069915832535093383_n.mp4?_nc_cat=108&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjIwMjksInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=_eaCxpJJm0AAX90MpeB&rl=2029&vabr=1353&_nc_ht=scontent-frt3-1.xx&oh=758e5d6c482b543f724e4ba2011100cb&oe=618A743A",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 12,
        "episodes": 12,
        "time": 24,
        "rating": 9.7,
        "user_rating": 386,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hài hước",
            "Đời thường",
            "Siêu nhiên"
        ],
        "year": 2021,
    },
    {
        "id": 16,
        "title": "Tensei shitara Slime Datta Ken",
        "description": "Một anh chàng bị tên cướp đâm chết khi đi gặp đồng nghiệp cùng vợ chưa cưới của cậu ta. Khi đang thoi thóp trước khi chết, người đầy máu, anh ta nghe được một tiếng nói kỳ lạ. Giọng nói ấy chuyển thể sự tiếc nuối của anh chàng vì vẫn còn tân trước khi đi và ban cho anh ta chiêu thức đặc biệt [tiên nhân vĩ đại]. Liệu đây có phải là trò đùa?",
        "image_title": "/resources/img/Tensei shitara Slime Datta Ken.jpg",
        "image_banner": "/resources/img/Tensei shitara Slime Datta Ken.jpg",
        "video": "https://scontent-frx5-1.xx.fbcdn.net/v/t66.36240-6/10000000_593222792098758_894438584320721950_n.mp4?_nc_cat=100&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjIyMTEsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=IdHAn7241UwAX9TknoK&rl=2211&vabr=1474&_nc_ht=scontent-frx5-1.xx&edm=APRAPSkEAAAA&oh=be8c0ef98afec500d41294e4496dee83&oe=618B4469",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 13,
        "episodes": 13,
        "time": 24,
        "rating": 9.8,
        "user_rating": 32628,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hài hước",
            "Phiêu lưu",
            "Ma thuật",
            "Siêu nhiên"
        ],
        "year": 2018,
    },
    {
        "id": 17,
        "title": "Tokyo Revengers",
        "description": "Mở đầu câu chuyện, Takemichi 26 tuổi, là một cậu thanh niên thất nghiệp, sống tại Tokyo nhận được tin cô bạn gái duy nhất của mình từ hồi sơ trung – Hinata qua đời trong một vụ ẩu đả giữa các băng nhóm tội phạm. Trong khoảnh khắc khi Takemichi bị đẩy xuống đường ray xe lửa, cậu đã vượt thời gian quay trở về thời còn học sơ trung. Nhận ra khả năng du hành thời gian của mình, Takemichi quyết tâm thay đổi tương lai và cứu lấy bạn gái bằng cách trở thành ông trùm băng đản khét tiếng nhất vùng Kanto.",
        "image_title": "/resources/img/Tokyo Revengers.jpg",
        "image_banner": "/resources/img/Tokyo Revengers.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_419341266444436_5395733168980211800_n.mp4?_nc_cat=107&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=gpvK7lXW1YgAX89R8q-&rl=1500&vabr=674&_nc_ht=scontent-frt3-1.xx&oh=26abeb928fb5455f7c8accc2205f6479&oe=6189F7E6",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 24,
        "episodes": 24,
        "time": 24,
        "rating": 9.0,
        "user_rating": 769,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hành động",
            "Học đường",
            "Drama"
        ],
        "year": 2021,
    },
    {
        "id": 18,
        "title": "Isekai Maou to Shoukan Shoujo no Dorei Majutsu Ω",
        "description": "Phần tiếp theo của tựa phim Isekai Maou to Shoukan Shoujo no Dorei Majutsu",
        "image_title": "/resources/img/Isekai Maou to Shoukan Shoujo no Dorei Majutsu.jpg",
        "image_banner": "/resources/img/Isekai Maou to Shoukan Shoujo no Dorei Majutsu.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_407144187695446_7193426385289788184_n.mp4?_nc_cat=110&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE2NzcsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=JDFTyaHeX3EAX9-WXP7&rl=1677&vabr=1118&_nc_ht=scontent-frx5-1.xx&oh=600acbea4fa1eac609e1215be007d2c6&oe=618982D1",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 10,
        "episodes": 10,
        "time": 24,
        "rating": 9.1,
        "user_rating": 583,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Tình cảm",
            "Hài hước",
            "Isekai",
            "Ma thuật"
        ],
        "year": 2021,
    },
    {
        "id": 19,
        "title": "Violet Evergarden Movie",
        "description": "Câu chuyện bên lề của bộ phim Violet Evergarden: Eternity and the Auto Memories Doll",
        "image_title": "/resources/img/Violet Evergarden.jpg",
        "image_banner": "/resources/img/Violet Evergarden.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_845714682779763_4473025362908555465_n.mp4?_nc_cat=101&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=HK6TJR3D3rUAX-NELf5&rl=1500&vabr=434&_nc_ht=scontent-frt3-2.xx&oh=ab018d195736ebbce06310d19452dc89&oe=618AFF21",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 1,
        "episodes": 1,
        "time": 140,
        "rating": 9.0,
        "user_rating": 380,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Tình cảm",
            "Đời thường",
            "Drama"
        ],
        "year": 2020,
    },
    {
        "id": 20,
        "title": "Horimiya",
        "description": "Dù được bạn bè ngưỡng mộ bởi học lực và sự tốt bụng, nữ sinh Kyouko Hori vẫn luôn che giấu 1 bộ mặt khác. Do bố mẹ luôn bận việc vắng nhà, cô luôn phải làm việc nhà và chăm sóc em trai, và không còn thời gian để sinh hoạt bên ngoài trường học.\
        Trong khi đó, Izumi Miyamura được xem là 1 otaku đeo kính u ám. Nhưng thực tế cậu là 1 chàng trai tốt bụng. Ngoài ra, cậu còn có 9 lỗ khuyên sau mái tóc dài và hình xăm dài ở vai trái và lưng.\
        Tình cờ thay, Hori và Miyamura đã gặp nhau bên ngoài trường học—hoàn toàn không giống với suy nghĩ của nhau. Hai con người đối lập dần trở thành bạn bè, cùng chia sẻ những khía cạnh mà họ chưa từng để lộ với người khác.",
        "image_title": "/resources/img/Horimiya.jpg",
        "image_banner": "/resources/img/Horimiya.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_272616814769818_7540846192791874829_n.mp4?_nc_cat=100&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=erpQydQEPCcAX91exr_&rl=1500&vabr=898&_nc_ht=scontent-frx5-1.xx&oh=7e58696a70cadf7659f3407bc64c3f65&oe=618AE7FD",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 12,
        "episodes": 12,
        "time": 24,
        "rating": 9.7,
        "user_rating": 1574,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Tình cảm",
            "Đời thường",
            "Học đường",
            "Hài hước"
        ],
        "year": 2021,
    },
    {
        "id": 21,
        "title": "Mieruko-chan",
        "description": "Miko là một học sinh cao trung điển hình có cuộc sống đảo lộn khi cô đột nhiên bắt đầu nhìn thấy những con quái vật ghê rợn và gớm ghiếc. Mặc dù hoàn toàn vô cùng sợ hãi, Miko vẫn tiếp tục cuộc sống hàng ngày của mình, giả vờ không để ý đến nỗi kinh hoàng đang bao quanh cô. Cô ấy phải chịu đựng nỗi sợ hãi để giữ cho mình và người bạn Hana của cô ấy thoát khỏi nguy hiểm, ngay cả khi điều đó có nghĩa là phải đối mặt với điều tồi tệ nhất. Pha trộn giữa hài kịch và kinh dị, Mieruko-chan kể câu chuyện về một cô gái cố gắng đối phó với điều huyền bí bằng cách tỏ ra thờ ơ với nó.",
        "image_title": "https://animehay.site/upload/poster/3340-1633164443.jpg",
        "image_banner": "https://animehay.site/upload/poster/3340-1633164443.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_121605426944400_7681696601290597501_n.mp4?_nc_cat=106&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=_Eki5FACwTYAX_K4kcg&_nc_oc=AQkXtnZZFc7N_9v5lSjLYqUPTkJZKt9Gt0eFdD7Qkz7fD5D3fqtRXzjmLw0UGcpceTuNcO39V9TgS7Ntab4YhOTL&rl=1500&vabr=706&_nc_ht=scontent-frt3-1.xx&oh=c55084e72390aa2054ab8ccac101e402&oe=618AF1A1",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 5,
        "episodes": 12,
        "time": 24,
        "rating": 9.7,
        "user_rating": 259,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Đời thường",
            "Kinh dị",
            "Hài hước"
        ],
        "year": 2021,
    },
    {
        "id": 22,
        "title": "Komi-san wa, Comyushou desu",
        "description": "Tadano Hitohito, một cậu chàng tầm thường được nhận học vào trường danh tiếng nhất vùng. Cứ tưởng rằng cuộc đời cao trung của mình sẽ yên bình. Trớ trêu thay, cậu lại ngồi cạnh bàn người đẹp Komi-san được coi là hoa khôi của trường ngày từ ngày đầu tiên đi học. Tồi tệ hơn khi cô hoa khôi này lại mắc phải chứng khó giao tiếp...",
        "image_title": "https://animehay.site//upload/poster/3369.jpg",
        "image_banner": "https://animehay.site//upload/poster/3369.jpg",
        "video": "https://video.fhph1-1.fna.fbcdn.net/v/t66.36240-6/10000000_163380819320601_781458447076999447_n.mp4?_nc_cat=110&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=hExdgUfjVQ0AX9aYWGy&_nc_oc=AQk83hbJBEkQgLBLX5WvC69ofL9oQhrEDhIOL7j36-20lYgadHlILA7PM2y4ZmzeMAJqSGQ_LGwpXm3qFT2i8st0&rl=1500&vabr=786&_nc_ht=scontent-frx5-1.xx&oh=bb5fb067176cf517d52f5c1c215bc375&oe=618A9FB9",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 5,
        "episodes": 12,
        "time": 24,
        "rating": 9.7,
        "user_rating": 420,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Đời thường",
            "Học đường",
            "Hài hước"
        ],
        "year": 2021,
    },
    {
        "id": 23,
        "title": "Senpai ga Uzai Kouhai no Hanashi",
        "description": "Igarashi là một nữ văn phòng trẻ tuổi chăm chỉ. Takeda là senpai của Igarashi trong văn phòng, luôn làm cô ấy khó chịu, nhưng giữa hai người họ lại càng ngày càng có nhiều sự gần gũi hơn, hiểu nhau hơn. Mỗi ngày trong văn phòng là một khoảnh khắc lãng mạn khi Igarashi cố gắng cân bằng giữa công việc, tình yêu và cuộc sống.",
        "image_title": "https://animehay.site//upload/poster/3364.jpg",
        "image_banner": "https://animehay.site//upload/poster/3364.jpg",
        "video": "https://video.fhph1-1.fna.fbcdn.net/v/t66.36240-6/10000000_413653063801846_7521400593072067725_n.mp4?_nc_cat=111&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=0djrf4C4QBIAX_HBOnh&rl=1500&vabr=648&_nc_ht=scontent-frx5-1.xx&oh=4bc83eb2de9b34584961f17d3529781c&oe=618B59C8",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 5,
        "episodes": 12,
        "time": 24,
        "rating": 9.5,
        "user_rating": 134,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Đời thường",
            "Tình cảm",
            "Hài hước"
        ],
        "year": 2021,
    },
    {
        "id": 24,
        "title": "Saihate no Paladin",
        "description": "Will, một cậu bé con người được sinh ra với ký ức mơ hồ về kiếp sống trước của mình. Cậu được ba undead nhận nuôi từ khi chỉ mới lọt lòng. Suốt thuở ấu thơ sống tách biệt với thế giới bên ngoài, cậu vô thức nhận ba kẻ dị loài kia trở thành gia đình của mình khi nào chẳng hay. Song tuy hạnh phúc là thế, dường như ba undead vẫn còn dụng ý nào khác?",
        "image_title": "https://animehay.site//upload/poster/3361.jpg",
        "image_banner": "https://animehay.site//upload/poster/3361.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_451523936321520_6228844238095236469_n.mp4?_nc_cat=103&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=W0Ijlc_Gnl4AX82GuYS&rl=1500&vabr=725&_nc_ht=scontent-frt3-2.xx&oh=7e20cd050e10548aeada01fbd8175a13&oe=618A8E47",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 5,
        "episodes": 24,
        "time": 24,
        "rating": 9.4,
        "user_rating": 233,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": false,
        "type": [
            "Hành động",
            "Viễn tưởng"
        ],
        "year": 2021,
    },
    {
        "id": 25,
        "title": "Tsuki ga Michibiku Isekai Douchuu",
        "description": "“Tại sao tôi lại ở đây? Cái chỗ quỷ quái này là sao chứ?”\
        Misumi Makoto vốn chỉ là một học sinh trung học bình thường, giỏi bắn cung và đam mê phim lịch sử. Nhưng rồi một ngày kia khi cậu tỉnh lại, thì bỗng phát hiện ra mình đang ở một nơi kỳ quái không để đâu cho hết! Một thế giới xa lạ, một nơi thậm chí còn không thuộc về Trái Đất?\
        Khi mà Makoto còn chưa kịp định thần thì Nữ thần cai quản ở cái thế giới thập phần quái dị này đã chê bai vẻ bề ngoài của cậu “Trông cái mặt ngươi gớm quá”, rồi đày cậu xuống nơi “Tận cùng của thế giới”!!\
        Nhưng Makoto cũng không vì thế mà bỏ cuộc hay chán nản, cậu bỏ mặc mọi qui định hay những nguyên tắc cứng nhắc nơi đây và tự mình bắt đầu cuộc hành trình đi tìm kiếm sự tồn tại của con người ở xứ sở xa lạ này. Cũng nhờ đó mà Makoto gặp được những người bạn đồng hành không ngờ tới: cô gái tên Orc tốt bụng luôn thơm ngát hương hoa cỏ, con nhện khổng lồ biến thái máu M và cả hóa thân của con rồng cuồng phim lịch sử nữa…\
        Cùng những người bạn không giống ai này, chuyến hành trình nào đang chờ đợi Makoto ở phía trước?",
        "image_title": "https://animehay.site/upload/poster/3285.jpg",
        "image_banner": "https://animehay.site/upload/poster/3285.jpg",
        "video": "https://video.fhph1-2.fna.fbcdn.net/v/t66.36240-6/10000000_451523936321520_6228844238095236469_n.mp4?_nc_cat=103&ccb=1-5&_nc_sid=985c63&efg=eyJybHIiOjE1MDAsInJsYSI6NDA5NiwidmVuY29kZV90YWciOiJvZXBfaGQifQ%3D%3D&_nc_ohc=W0Ijlc_Gnl4AX82GuYS&rl=1500&vabr=725&_nc_ht=scontent-frt3-2.xx&oh=7e20cd050e10548aeada01fbd8175a13&oe=618A8E47",
        "episode": 1,
        "link_info": "#",
        "link_watch": "#",
        "episode_lastes": 12,
        "episodes": 12,
        "time": 24,
        "rating": 9.6,
        "user_rating": 1038,
        "view": 243390,
        "studio": "A1-ufotable",
        "age_limit": 16,
        "love": 1217,
        "status": true,
        "type": [
            "Hành động",
            "Phiêu lưu",
            "Viễn tưởng"
        ],
        "year": 2021,
    },
]

export default data